package model
{
	import Icon.CALC;
	import Icon.LED_DE;
	import Icon.LED_IN;
	import Icon.LED_TOGGLE;
	import Icon.MAIL;
	import Icon.MNXT;
	import Icon.MPLY;
	import Icon.MPRV;
	import Icon.MSTP;
	import Icon.MUTE;
	import Icon.VOLD;
	import Icon.VOLU;
	import Icon.WHOM;

	public class ConfigManager
	{
		private static const keylabel:Object={
			
			'KC_NO':{c:'No',d:'No'},
			'KC_TRNS':{c:'',d:'Trns'},
			'KC_A':{t:'A',d:'A'},
			'KC_B':{t:'B',d:'B'},
			'KC_C':{t:'C',d:'C'},
			'KC_D':{t:'D',d:'D'},
			'KC_E':{t:'E',d:'E'},
			'KC_F':{t:'F',d:'F'},
			'KC_G':{t:'G',d:'G'},
			'KC_H':{t:'H',d:'H'},
			'KC_I':{t:'I',d:'I'},
			'KC_J':{t:'J',d:'J'},
			'KC_K':{t:'K',d:'K'},
			'KC_L':{t:'L',d:'L'},
			'KC_M':{t:'M',d:'M'},
			'KC_N':{t:'N',d:'N'},
			'KC_O':{t:'O',d:'O'},
			'KC_P':{t:'P',d:'P'},
			'KC_Q':{t:'Q',d:'Q'},
			'KC_R':{t:'R',d:'R'},
			'KC_S':{t:'S',d:'S'},
			'KC_T':{t:'T',d:'T'},
			'KC_U':{t:'U',d:'U'},
			'KC_V':{t:'V',d:'V'},
			'KC_W':{t:'W',d:'W'},
			'KC_X':{t:'X',d:'X'},
			'KC_Y':{t:'Y',d:'Y'},
			'KC_Z':{t:'Z',d:'Z'},
			'KC_1':{t:'!',b:'1',d:'1 !'},
			'KC_2':{t:'@',b:'2',d:'2 @'},
			'KC_3':{t:'#',b:'3',d:'3 #'},
			'KC_4':{t:'$',b:'4',d:'4 $'},
			'KC_5':{t:'%',b:'5',d:'5 %'},
			'KC_6':{t:'^',b:'6',d:'6 ^'},
			'KC_7':{t:'&',b:'7',d:'7 &'},
			'KC_8':{t:'*',b:'8',d:'8 *'},
			'KC_9':{t:'(',b:'9',d:'9 ('},
			'KC_0':{t:')',b:'0',d:'0 )'},
			'KC_ENT':{c:'Enter',d:'Enter'},
			'KC_ESC':{c:'Esc',d:'Esc'},
			'KC_BSPC':{c:'BackSpace',min:2,sc:'BS',d:'BackSpace'},
			'KC_TAB':{c:'Tab',d:'Tab'},
			'KC_SPC':{c:'Space',d:'Space'},
			'KC_MINS':{t:'—',b:'﹣',d:'﹣'},
			'KC_EQL':{t:'+',b:'=',d:'= +'},
			'KC_LBRC':{t:'{',b:'[',d:'[ {'},	
			'KC_RBRC':{t:'}',b:']',d:'] }'},
			'KC_BSLS':{t:'¦',b:'\\',d:'\\ ¦'},
			'KC_NUHS':{t:'~',b:'#',d:'# ~'},
			'KC_SCLN':{t:':',b:';',d:'; :'},
			'KC_QUOT':{t:'"',b:'\'',d:'\' "'},
			'KC_GRV':{t:'~',b:'`',d:'` ~'},
			'KC_COMM':{t:'<',b:',',d:', <'},
			'KC_DOT':{t:'>',b:'.',d:'. >'},
			'KC_SLSH':{t:'?',b:'/',d:'/ ?'},
			'KC_CAPS':{c:'Caps Lock',d:'Caps Lock'},
			'KC_F1':{c:'F1',d:'F1'},
			'KC_F2':{c:'F2',d:'F2'},
			'KC_F3':{c:'F3',d:'F3'},
			'KC_F4':{c:'F4',d:'F4'},
			'KC_F5':{c:'F5',d:'F5'},
			'KC_F6':{c:'F6',d:'F6'},
			'KC_F7':{c:'F7',d:'F7'},
			'KC_F8':{c:'F8',d:'F8'},
			'KC_F9':{c:'F9',d:'F9'},
			'KC_F10':{c:'F10',d:'F10'},
			'KC_F11':{c:'F11',d:'F11'},
			'KC_F12':{c:'F12',d:'F12'},
			'KC_PSCR':{t:'Prtsrc',b:'Sysreq',min:1.5,st:'Prt',sb:'Src',d:'Prtsrc Sysreq'},
			'KC_SLCK':{t:'Scroll',b:'Lock',d:'Scroll Lock',min:1.5,st:'Scrl',sb:'Lck'},
			'KC_PAUS':{t:'Pause',b:'Break',d:'Pause Break',min:1.5,st:'Pus',sb:'Brk'},
			'KC_INS':{c:'Insert',d:'Insert',min:1.5,sc:'Ins'},
			'KC_HOME':{c:'Home',d:'home'},
			'KC_PGUP':{t:'Page',b:'Up',d:'PageUp'},
			'KC_DEL':{c:'Delete',d:'Delete'},
			'KC_END':{c:'End',d:'End'},
			'KC_PGDN':{t:'Page',b:'Down',d:'PageDown'},
			'KC_RGHT':{t:'→',d:'Right'},
			'KC_LEFT':{t:'←',d:'Left'},
			'KC_DOWN':{t:'↓',d:'Down'},
			'KC_UP':{t:'↑',d:'Up'},				
			'KC_NLCK':{t:'Num',b:'Lock',d:'Num Lock'},				
			'KC_PSLS':{c:'/',d:'KeyPad /'},				
			'KC_PAST':{c:'*',d:'KeyPad *'},				
			'KC_PMNS':{c:'—',d:'KeyPad —'},				
			'KC_PPLS':{c:'+',d:'KeyPad +'},				
			'KC_PENT':{c:'Enter',d:'KeyPad Enter'},				
			'KC_P1':{t:'1',b:'End',d:'KeyPad 1'},				
			'KC_P2':{t:'2',b:'↑',d:'KeyPad 2'},				
			'KC_P3':{t:'3',b:'PgDn',d:'KeyPad 3'},				
			'KC_P4':{t:'4',b:'←',d:'KeyPad 4'},				
			'KC_P5':{t:'5',d:'KeyPad 5'},				
			'KC_P6':{t:'6',b:'→',d:'KeyPad 6'},				
			'KC_P7':{t:'7',b:'Home',d:'KeyPad 7'},				
			'KC_P8':{t:'8',b:'↑',d:'KeyPad 8'},				
			'KC_P9':{t:'9',b:'PgUp',d:'KeyPad 9'},				
			'KC_P0':{t:'0',b:'Ins',d:'KeyPad 0'},				
			'KC_PDOT':{t:'.',b:'Del',d:'KeyPad .'},				
			'KC_PEQL':{c:'=',d:'KeyPad ='},				
			'KC_F13':{c:'F13',d:'F13'},
			'KC_F14':{c:'F14',d:'F14'},
			'KC_F15':{c:'F15',d:'F15'},
			'KC_F16':{c:'F16',d:'F16'},
			'KC_F17':{c:'F17',d:'F17'},
			'KC_F18':{c:'F18',d:'F18'},
			'KC_F19':{c:'F19',d:'F19'},
			'KC_F20':{c:'F20',d:'F20'},
			'KC_F21':{c:'F21',d:'F21'},
			'KC_F22':{c:'F22',d:'F22'},
			'KC_F23':{c:'F23',d:'F23'},
			'KC_F24':{c:'F24',d:'F24'},		
			'KC_EXECUTE':{c:'Execute'},		
			'KC_HELP':{c:'Help'},		
			'KC_APP':{c:'Menu',d:'MENU'},		
			'KC_SELECT':{c:'Select'},		
			'KC_STOP':{c:'Stop'},		
			'KC_AGAIN':{c:'Again'},		
			'KC_CUT':{c:'Cut'},		
			'KC_COPY':{c:'Copy'},		
			'KC_PASTE':{c:'Paste'},		
			'KC_FIND':{c:'Find'},		
			'KC__MUTE':{c:'Mute'},		
			'KC__VOLUP':{t:'Volume',c:'Up'},		
			'KC__VOLDOWN':{t:'Volume',c:'Down'},		
			'KC_LOCKING_CAPS':{t:'Locking',c:'Caps',b:'Lock'},		
			'KC_LOCKING_NUM':{t:'Locking',c:'Num',b:'Lock'},		
			'KC_LOCKING_SCROLL':{t:'Locking',c:'Scroll',b:'Lock'},		
			'KC_PCMM':{c:','},
			'KC_KP_EQUAL_AS400':{c:'='},
			'KC_RO':{c:'int1'},
			'KC_KANA':{c:'int2'},
			'KC_JYEN':{c:'int3'},
			'KC_HENK':{c:'int4'},
			'KC_MHEN':{c:'int5'},
			'KC_INT6':{c:'int6'},
			'KC_INT7':{c:'int7'},
			'KC_INT8':{c:'int8'},
			'KC_INT9':{c:'int9'},
			'KC_LANG1':{c:'lang1'},
			'KC_LANG2':{c:'lang2'},
			'KC_LANG3':{c:'lang3'},
			'KC_LANG4':{c:'lang4'},
			'KC_LANG5':{c:'lang5'},
			'KC_LANG6':{c:'lang6'},
			'KC_LANG7':{c:'lang7'},
			'KC_LANG8':{c:'lang8'},
			'KC_LANG9':{c:'lang9'},
			'KC_ALT_ERASE':{t:'Alt',b:'Erase'},
			'KC_SYSREQ':{c:'SysReq'},
			'KC_CANCEL':{c:'Cancel'},
			'KC_CLEAR':{c:'Clear'},
			'KC_PRIOR':{c:'Prior'},
			'KC_RETURN':{c:'Return'},
			'KC_SEPARATOR':{c:'Separator'},
			'KC_OUT':{c:'Out'},
			'KC_OPER':{c:'Oper'},
			'KC_CLEAR_AGAIN':{t:'Clear',b:'Again'},
			'KC_CRSEL':{t:'CrSel',b:'Props'},
			'KC_EXSEL':{t:'ExSel'},
			
			'KC_LCTRL':{c:'Ctrl',d:'LCtrl'},
			'KC_LSFT':{c:'Shift',d:'LShift'},
			'KC_LALT':{c:'Alt',d:'LAlt'},
			'KC_LGUI':{c:'Win',d:'LWin'},
			'KC_RCTRL':{c:'Ctrl',d:'RAlt'},
			'KC_RSFT':{c:'Shift',d:'RShift'},
			'KC_RALT':{c:'Alt',d:'RAlt'},
			'KC_RGUI':{c:'Win',d:'RWin'},
			'KC_PWR':{t:'Power',b:'Down',d:'Power Down'},
			'KC_SLEP':{t:'System',b:'Sleep',d:'System Sleep'},
			'KC_WAKE':{t:'System',b:'Wake',d:'System Wake'},
			'KC_MUTE':{i:Icon.MUTE},
			'KC_VOLU':{i:Icon.VOLU},
			'KC_VOLD':{i:Icon.VOLD},
			'KC_MNXT':{i:Icon.MNXT},
			'KC_MPRV':{i:Icon.MPRV},
			'KC_MSTP':{i:Icon.MSTP},
			'KC_MPLY':{i:Icon.MPLY},
			'KC_MSEL':{c:'KC_MSEL'},
			'KC_MAIL':{i:Icon.MAIL},
			'KC_CALC':{i:Icon.CALC},
			'KC_MYCM':{c:'KC_MYCM'},
			'KC_WSCH':{c:'KC_WSCH'},
			'KC_WHOM':{i:Icon.WHOM},
			'KC_WBAK':{c:'KC_WBAK'},
			'KC_WFWD':{c:'KC_WFWD'},
			'KC_WSTP':{c:'KC_WSTP'},
			'KC_WREF':{c:'KC_WREF'},
			'KC_WFAV':{c:'KC_WFAV'},
			
			'KC_MS_U':{c:'KC_MS_U'},
			'KC_MS_D':{c:'KC_MS_D'},
			'KC_MS_L':{c:'KC_MS_L'},
			'KC_MS_R':{c:'KC_MS_R'},
			'KC_BTN1':{c:'KC_BTN1'},
			'KC_BTN2':{c:'KC_BTN2'},
			'KC_BTN3':{c:'KC_BTN3'},
			'KC_BTN4':{c:'KC_BTN4'},
			'KC_BTN5':{c:'KC_BTN5'},
			'KC_WH_U':{c:'KC_BTN5'},
			'KC_WH_D':{c:'KC_WH_D'},
			'KC_WH_L':{c:'KC_WH_L'},
			'KC_WH_R':{c:'KC_WH_R'},
			'KC_ACL0':{c:'KC_ACL0'},
			'KC_ACL1':{c:'KC_ACL1'},
			'KC_ACL2':{c:'KC_ACL2'},
			
			'KC_FN':{c:'Fn'},
			'KC_FN0':{c:'Fn0'},
			'KC_FN1':{c:'Fn1'},
			'KC_FN2':{c:'Fn2'},
			'KC_FN3':{c:'Fn3'},
			'KC_FN4':{c:'Fn4'},
			'KC_FN5':{c:'Fn5'},
			'KC_FN6':{c:'Fn6'},
			'KC_FN7':{c:'Fn7'},
			'KC_FN8':{c:'Fn8'},
			'KC_FN9':{c:'Fn9'},
			'KC_FN10':{c:'Fn10'},
			'KC_FN11':{c:'Fn11'},
			'KC_FN12':{c:'Fn12'},
			'KC_FN13':{c:'Fn13'},
			'KC_FN14':{c:'Fn14'},
			'KC_FN15':{c:'Fn15'},
			'KC_FN16':{c:'Fn16'},
			'KC_FN17':{c:'Fn17'},
			'KC_FN18':{c:'Fn18'},
			'KC_FN19':{c:'Fn19'},
			'KC_FN20':{c:'Fn20'},
			'KC_FN21':{c:'Fn21'},
			'KC_FN22':{c:'Fn22'},
			'KC_FN23':{c:'Fn23'},
			'KC_FN24':{c:'Fn24'},
			'KC_FN25':{c:'Fn25'},
			'KC_FN26':{c:'Fn26'},
			'KC_FN27':{c:'Fn27'},
			'KC_FN28':{c:'Fn28'},
			'KC_FN29':{c:'Fn29'},
			'KC_FN30':{c:'Fn30'},
			'KC_FN31':{c:'Fn31'},
			'KC_LED_IN':{i:Icon.LED_IN},
			'KC_LED_DE':{i:Icon.LED_DE},
			'KC_LED_TOGGLE':{i:Icon.LED_TOGGLE},
			'KC_SFT_ESC':{t:'Esc',b:'~',d:'Esc and ~'}
			
		};
		
		public static const virtualKeyboardConfig:Array=[
			'KC_TRNS','KC_NO','KC_LED_IN','KC_LED_DE','KC_LED_TOGGLE','KC_VOLU','KC_VOLD','KC_MUTE','KC_CALC','KC_MAIL','KC_WHOM',
			'KC_ESC','KC_SFT_ESC','KC_F1','KC_F2','KC_F3','KC_F4','KC_F5','KC_F6','KC_F7','KC_F8','KC_F9','KC_F10','KC_F11','KC_F12','KC_PSCR','KC_SLCK','KC_PAUS','KC_MPLY','KC_MSTP','KC_MPRV','KC_MNXT',
			'KC_GRV','KC_1','KC_2','KC_3','KC_4','KC_5','KC_6','KC_7','KC_8','KC_9','KC_0','KC_MINS','KC_EQL','KC_BSPC','KC_INS','KC_HOME','KC_PGUP','KC_NLCK','KC_PSLS','KC_PAST','KC_PMNS',
			'KC_TAB','KC_Q','KC_W','KC_E','KC_R','KC_T','KC_Y','KC_U','KC_I','KC_O','KC_P','KC_LBRC','KC_RBRC','KC_BSLS','KC_DEL','KC_END','KC_PGDN','KC_P7','KC_P8','KC_P9','KC_PPLS',
			'KC_CAPS','KC_A','KC_S','KC_D','KC_F','KC_G','KC_H','KC_J','KC_K','KC_L','KC_SCLN','KC_QUOT','KC_ENT','KC_P4','KC_P5','KC_P6',
			'KC_LSFT','KC_Z','KC_X','KC_C','KC_V','KC_B','KC_N','KC_M','KC_COMM','KC_DOT','KC_SLSH','KC_RSFT','KC_UP','KC_P1','KC_P2','KC_P3','KC_PENT',
			'KC_LCTRL','KC_LGUI','KC_LALT','KC_SPC','KC_RALT','KC_RGUI','KC_APP','KC_RCTRL','KC_LEFT','KC_DOWN','KC_RGHT','KC_P0','KC_PDOT'
		];
		public static const fnTypeList:Array=[
			{'action':'ACTION_NO','args':[],'type':0}
			,{'action':'ACTION_LAYER_MOMENTARY','args':[1],'type':1}
			,{'action':'ACTION_LAYER_ON','args':[1,1],'type':2}
			,{'action':'ACTION_LAYER_OFF','args':[1,1],'type':2}
			,{'action':'ACTION_LAYER_TOGGLE','args':[1],'type':1}
			,{'action':'ACTION_LAYER_TAP_KEY','args':[1,'KC_NO'],'type':3}
			,{'action':'ACTION_MODS','args':[0,0,0,0],'type':4}
			,{'action':'ACTION_MODS_KEY','args':[0,0,0,0,'KC_NO'],'type':5}
			,{'action':'ACTION_MODS_ONESHOT','args':[0,0,0,0],'type':4}
			,{'action':'ACTION_MODS_TAP_TOGGLE','args':[0,0,0,0],'type':4}
			,{'action':'ACTION_LAYER_CLEAR','args':[1],'type':6}
		];
		
		public static function keyCodeToLabel(ks:String):Object
		{
			if(keylabel[ks]){
				return keylabel[ks];
			}
			return null;
		}
	}
}